language: go

# Go major releases are supported until there are two newer major releases; security patches are made available in supported releases.
# (https://golang.org/doc/devel/release.html)
go:
    - "1.9.x"
    - "1.10.x"
    - "master" # test against future releases

matrix:
    allow_failures:
        - go: "master" # allow master to fail
    fast_finish: true # determine build result as soon as the required jobs finish

before_install:
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh # install dep (https://golang.github.io/dep/docs/installation.html)

install:
    - dep ensure -add github.com/mattn/goveralls@v0.0.2 # install dependencies + goveralls
    - go install ./vendor/github.com/mattn/goveralls # build goveralls

script:
    - $GOPATH/bin/goveralls -service=travis-ci
