// Code generated by slices-gen -- DO NOT EDIT

package slices

// ByteSlice is a slice of byte's.
type ByteSlice []byte

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s ByteSlice) Contains(value byte) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
