// Code generated by slices-gen -- DO NOT EDIT

package slices

// Uint64Slice is a slice of uint64's.
type Uint64Slice []uint64

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s Uint64Slice) Contains(value uint64) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
