// Code generated by slices-gen -- DO NOT EDIT
// generated at 2018-03-04 20:13:49.410154498 -0800 PST m=+0.000977763

package util

// Uint64Slice is a slice of uint64's.
type Uint64Slice []uint64

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s Uint64Slice) Contains(value uint64) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
