// Code generated by slices-gen -- DO NOT EDIT

package slices

// Uint8Slice is a slice of uint8's.
type Uint8Slice []uint8

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s Uint8Slice) Contains(value uint8) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
