// Code generated by slices-gen -- DO NOT EDIT
// generated at 2018-03-04 20:13:49.176170393 -0800 PST m=+0.001005914

package util

// Uint32Slice is a slice of uint32's.
type Uint32Slice []uint32

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s Uint32Slice) Contains(value uint32) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
