// Code generated by slices-gen -- DO NOT EDIT
// generated at 2018-03-04 20:13:49.614243745 -0800 PST m=+0.001045946

package util

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("ByteSlice", func() {
	// More of a static assertion, but eh:
	It("is a slice of byte's", func() {
		var s ByteSlice = []byte{1, 2, 3}
		s[0] = 0 // prevent unused error
	})

	_ = Describe(".Contains", func() {
		It("returns true if the provided value is in the slice", func() {
			s := ByteSlice{1, 2, 3, 4, 5}
			Expect(s.Contains(4)).To(BeTrue())
		})

		It("returns false if the provided value is not in the slice", func() {
			s := ByteSlice{1, 2, 3, 4, 5}
			Expect(s.Contains(42)).To(BeFalse())
		})
	})
})
