// Code generated by slices-gen -- DO NOT EDIT

package slices

// Int8Slice is a slice of int8's.
type Int8Slice []int8

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s Int8Slice) Contains(value int8) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
