// Code generated by slices-gen -- DO NOT EDIT

package slices

// Int64Slice is a slice of int64's.
type Int64Slice []int64

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s Int64Slice) Contains(value int64) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
