// Code generated by slices-gen -- DO NOT EDIT

package slices

// IntSlice is a slice of int's.
type IntSlice []int

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s IntSlice) Contains(value int) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
