// Code generated by slices-gen -- DO NOT EDIT
// generated at 2018-03-04 20:21:42.523646554 -0800 PST m=+0.000986474

package slices

// Int64Slice is a slice of int64's.
type Int64Slice []int64

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s Int64Slice) Contains(value int64) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
