// Code generated by slices-gen -- DO NOT EDIT
// generated at 2018-03-04 20:21:42.523646554 -0800 PST m=+0.000986474

package slices

import (
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("Int64Slice", func() {
	// More of a static assertion, but eh:
	It("is a slice of int64's", func() {
		var s Int64Slice = []int64{1, 2, 3}
		s[0] = 0 // prevent unused error
	})

	_ = Describe(".Contains", func() {
		It("returns true if the provided value is in the slice", func() {
			s := Int64Slice{1, 2, 3, 4, 5}
			Expect(s.Contains(4)).To(BeTrue())
		})

		It("returns false if the provided value is not in the slice", func() {
			s := Int64Slice{1, 2, 3, 4, 5}
			Expect(s.Contains(42)).To(BeFalse())
		})
	})
})
