// Code generated by slices-gen -- DO NOT EDIT
// generated at 2018-03-04 20:13:48.330867881 -0800 PST m=+0.000959482

package util

// Int32Slice is a slice of int32's.
type Int32Slice []int32

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s Int32Slice) Contains(value int32) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
