// Code generated by slices-gen -- DO NOT EDIT
// generated at 2018-03-04 20:21:41.33079667 -0800 PST m=+0.000982017

package slices

// IntSlice is a slice of int's.
type IntSlice []int

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s IntSlice) Contains(value int) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
