// Code generated by slices-gen -- DO NOT EDIT
// generated at 2018-03-04 20:13:49.819823231 -0800 PST m=+0.001284460

package util

// RuneSlice is a slice of rune's.
type RuneSlice []rune

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s RuneSlice) Contains(value rune) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
