// Code generated by slices-gen -- DO NOT EDIT

package slices

// Int16Slice is a slice of int16's.
type Int16Slice []int16

// Contains determines if the provided value is present in the slice.
// Runtime: O(n) -- appropriate for small-n slices.
func (s Int16Slice) Contains(value int16) bool {
	for _, v := range s {
		if v == value {
			return true
		}
	}

	return false
}
